/**
 * BPM4B Standalone EPUB Tool
 * Optimized for CLI usage and production workflows
 */

const pdfParse = require('pdf-parse');
const mammoth = require('mammoth');
const EPub = require('epub2');
const fs = require('fs').promises;
const path = require('path');

// Document format to EPUB logic
async function convertToEpub(inputPath, outputPath, metadata = {}) {
    const ext = path.extname(inputPath).toLowerCase();
    
    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    let text = '';
    let title = metadata.title || path.basename(inputPath, ext);
    let author = metadata.author || 'BPM4B Producer';

    console.log(`[EPUB-TOOL] Processing: ${inputPath}`);

    try {
        if (ext === '.pdf') {
            const dataBuffer = await fs.readFile(inputPath);
            const pdfData = await pdfParse(dataBuffer);
            text = pdfData.text;
        } else if (ext === '.docx') {
            const result = await mammoth.extractRawText({ path: inputPath });
            text = result.value;
        } else if (['.txt', '.md', '.rtf', '.html'].includes(ext)) {
            const buffer = await fs.readFile(inputPath);
            text = buffer.toString('utf-8');
            if (ext === '.html') {
                text = text.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
            }
        } else {
            throw new Error(`Unsupported format: ${ext}`);
        }

        const chapters = splitIntoChapters(text);
        await createEpub(chapters, outputPath, {
            title,
            author,
            genre: metadata.genre || 'General',
            description: metadata.description || 'Generated by BPM4B',
            language: metadata.language || 'en'
        });

        console.log(`[EPUB-TOOL] Success! Saved to: ${outputPath}`);
        return { success: true, path: outputPath };
    } catch (err) {
        console.error(`[EPUB-TOOL] Error: ${err.message}`);
        return { success: false, error: err.message };
    }
}

function splitIntoChapters(text) {
    // Simple split logic for CLI tool
    const paragraphs = text.split(/\n\n+/);
    const chapters = [];
    let currentChapter = '';
    let chapterIndex = 1;

    for (const para of paragraphs) {
        if (currentChapter.length + para.length > 8000) {
            chapters.push({ title: `Chapter ${chapterIndex++}`, content: currentChapter.trim() });
            currentChapter = para;
        } else {
            currentChapter += '\n\n' + para;
        }
    }
    if (currentChapter.trim()) {
        chapters.push({ title: `Chapter ${chapterIndex}`, content: currentChapter.trim() });
    }
    return chapters;
}

async function createEpub(chapters, outputPath, metadata) {
    return new Promise((resolve, reject) => {
        const epub = new EPub(outputPath, metadata.title, metadata.author);
        epub.on('error', reject);
        epub.on('end', resolve);
        epub.init();
        
        epub.metadata.title = metadata.title;
        epub.metadata.creator = metadata.author;
        epub.metadata.subject = metadata.genre;
        epub.metadata.description = metadata.description;
        epub.metadata.language = metadata.language;

        chapters.forEach((ch, i) => {
            epub.addChapter(`ch_${i}`, `ch_${i}.xhtml`, ch.title, `<h1>${ch.title}</h1><p>${ch.content.replace(/\n/g, '</p><p>')}</p>`);
        });

        epub.write();
    });
}

module.exports = { convertToEpub };
